import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const products = [
  { id: 1, name: 'Gold Standard Whey', ar: 'بروتين Gold Standard Whey', brand: 'Optimum Nutrition', category: 'بروتين', price: 78000, old: 92000, rating: 4.8, reviews: 1245, image: 'whey', badge: '-15%', detail: '24g بروتين • 5.5g BCAA • 2.3kg' },
  { id: 2, name: 'Creatine Monohydrate', ar: 'كرياتين مونوهيدرات', brand: 'Optimum Nutrition', category: 'كرياتين', price: 55000, old: 65000, rating: 4.7, reviews: 634, image: 'creatine', badge: '-15%', detail: '300g • 60 حصة • بدون نكهة' },
  { id: 3, name: 'Serious Mass', ar: 'سيريوس ماس لزيادة الوزن', brand: 'Optimum Nutrition', category: 'مكملات الوزن', price: 115000, old: 138000, rating: 4.6, reviews: 892, image: 'mass', badge: '-18%', detail: '2.7kg • 1250 سعرة • 50g بروتين' },
  { id: 4, name: 'Daily Vits', ar: 'فيتامينات يومية', brand: 'NOW Foods', category: 'فيتامينات', price: 28000, old: 35000, rating: 4.5, reviews: 321, image: 'vitamins', badge: '-20%', detail: '100 كبسولة • دعم يومي متكامل' },
  { id: 5, name: 'Mass Tech Elite', ar: 'ماس تك إليت', brand: 'MuscleTech', category: 'مكملات الوزن', price: 99000, old: 118000, rating: 4.4, reviews: 412, image: 'mass2', badge: 'عرض', detail: '3kg • زيادة الكتلة العضلية' },
  { id: 6, name: 'Pre JYM', ar: 'بري جيم', brand: 'JYM Supplement Science', category: 'Pre Workout', price: 68000, old: 76000, rating: 4.6, reviews: 189, image: 'pre', badge: 'جديد', detail: '30 حصة • طاقة وتركيز' }
];

const cats = [
  ['بروتين', 'بناء عضلات أقوى', 'whey'], ['كرياتين', 'قوة وأداء أعلى', 'creatine'], ['مكملات الوزن', 'زيادة الكتلة العضلية', 'mass'], ['فيتامينات', 'صحة أفضل كل يوم', 'vitamins'], ['الإكسسوارات', 'كل ما تحتاجه لتمرينك', 'gear']
];

const Icon = ({ name, size = 20 }) => {
  const paths = { search:'M11 4a7 7 0 1 0 4.9 12L21 21M4 11a7 7 0 0 1 7-7', cart:'M3 4h2l2 11h10l3-8H7M9 20h.01M17 20h.01', user:'M20 21a8 8 0 0 0-16 0M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8', heart:'M20.8 8.6c0 5.5-8.8 10.4-8.8 10.4S3.2 14.1 3.2 8.6A4.6 4.6 0 0 1 12 6.1a4.6 4.6 0 0 1 8.8 2.5Z', grid:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', compare:'M7 7h12l-3-3M17 17H5l3 3', menu:'M4 6h16M4 12h16M4 18h16', star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1 6.2-5.5-3-5.5 3 1-6.2L3 9.6l6.2-.9z'};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.grid}/></svg>
};

function Logo(){ return <div className="logo"><div className="logo-mark">CG</div><div><strong>CARBON GROUP</strong><span>NUTRITION</span></div></div> }
function ProductArt({ kind, large=false }){ return <div className={`product-art art-${kind} ${large?'large':''}`}><div className="jar-cap"/><div className="jar-label"><small>100% PURE</small><b>{kind === 'whey' ? 'WHEY' : kind === 'creatine' ? 'CREATINE' : kind === 'vitamins' ? 'VITS' : kind === 'pre' ? 'PRE' : 'MASS'}</b><em>CARBON</em></div></div> }
function ProductCard({ p, onAdd, onCompare, compared }){ return <article className="product-card"><div className="product-top"><span className="badge">{p.badge}</span><button className="icon-btn" aria-label="favorite"><Icon name="heart" size={18}/></button></div><ProductArt kind={p.image}/><div className="product-copy"><small>{p.brand}</small><h3>{p.ar}</h3><div className="rating"><span>★</span> {p.rating} <i>({p.reviews})</i></div><p className="price">{p.price.toLocaleString('en-US')} <small>د.ع</small> <del>{p.old.toLocaleString('en-US')}</del></p><div className="product-actions"><button className="add" onClick={()=>onAdd(p)}>أضف للسلة</button><button className={`compare ${compared?'selected':''}`} onClick={()=>onCompare(p)}><Icon name="compare" size={17}/></button></div></div></article> }

function App(){
  const [cart, setCart] = useState([]); const [compare, setCompare] = useState([products[0], products[1]]); const [query, setQuery] = useState(''); const [view, setView] = useState('store'); const [chat, setChat] = useState(false); const [toast, setToast] = useState('');
  const filtered = useMemo(()=>products.filter(p => `${p.ar} ${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const add = p => { setCart(c=>[...c,p]); setToast(`تمت إضافة ${p.ar} إلى السلة`); setTimeout(()=>setToast(''),2200) };
  const toggleCompare = p => setCompare(c=>c.some(x=>x.id===p.id)?c.filter(x=>x.id!==p.id):c.length<4?[...c,p]:c);
  if(view==='admin') return <Admin onBack={()=>setView('store')}/>;
  return <div className="app-shell">
    <div className="service-strip"><span>✓ منتجات أصلية 100%</span><span>▣ توصيل سريع لجميع المحافظات</span><span>◈ دعم فني مميز 24/7</span><span>★ أفضل العلامات العالمية</span></div>
    <header className="site-header"><button className="mobile-menu"><Icon name="menu"/></button><Logo/><nav><a className="active">الرئيسية</a><a onClick={()=>document.getElementById('products').scrollIntoView()}>منتجات البروتين</a><a>الكرياتين</a><a>مكملات الوزن</a><a>الفيتامينات</a><a>الإكسسوارات</a><a>العروض</a><a>العلامات</a></nav><div className="head-tools"><button><Icon name="heart"/><span>المفضلة</span></button><button><Icon name="user"/><span>حسابي</span></button><button className="cart-tool" onClick={()=>setToast(`لديك ${cart.length} منتجات في السلة`)}><Icon name="cart"/><span>سلة المشتريات</span>{cart.length>0&&<b>{cart.length}</b>}</button></div></header>
    <div className="mobile-search search-box"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="إبحث عن منتجاتك المفضلة..."/></div>
    <main>
      <section className="hero"><div className="hero-photo"><div className="gym-light"/><div className="athlete-silhouette"/></div><div className="hero-content"><h1>ابنِ أفضل نسخة<br/><span>من نفسك</span></h1><p>مكملات غذائية أصلية 100%<br/>لأداء أقوى ونتائج أكبر</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById('products').scrollIntoView()}>تسوق الآن <b>‹</b></button><button className="ghost">اكتشف العروض</button></div></div><div className="hero-products"><ProductArt kind="whey" large/><ProductArt kind="creatine" large/><ProductArt kind="mass" large/></div><div className="hero-dots"><b/><i/><i/></div></section>
      <section className="category-row">{cats.map(([name,sub,img])=><button className="category-card" key={name} onClick={()=>setQuery(name)}><ProductArt kind={img}/><div><h3>{name}</h3><p>{sub}</p></div><span>←</span></button>)}</section>
      <section className="compare-panel"><div className="section-head"><div><h2>مقارنة المنتجات</h2><p>اختر منتجات لمقارنة المكونات والسعر والقيم الغذائية</p></div><button className="outline" onClick={()=>setCompare([])}>مسح المقارنة</button></div><div className="compare-grid">{compare.map(p=><div className="compare-item" key={p.id}><button onClick={()=>toggleCompare(p)}>×</button><ProductArt kind={p.image}/><strong>{p.ar}</strong><span>{p.price.toLocaleString('en-US')} د.ع</span></div>)}<button className="compare-add" onClick={()=>document.getElementById('products').scrollIntoView()}><b>＋</b><span>إضافة منتج للمقارنة</span></button></div><button className="primary compare-cta" onClick={()=>setToast('تم فتح المقارنة التفصيلية')}>عرض المقارنة التفصيلية <Icon name="compare" size={18}/></button></section>
      <section id="products" className="products-section"><div className="section-head"><div><h2>الأكثر مبيعاً</h2><p>منتجات يختارها الرياضيون لتحقيق أفضل النتائج</p></div><button className="text-btn">عرض الكل ←</button></div><div className="products-grid">{filtered.map(p=><ProductCard key={p.id} p={p} onAdd={add} onCompare={toggleCompare} compared={compare.some(x=>x.id===p.id)}/>)}</div></section>
      <section className="offer-band"><div><h2>عروض خاصة</h2><p>أفضل الأسعار على منتجات مختارة لفترة محدودة</p></div><button className="primary">عرض جميع العروض</button><div className="offer-mini"><ProductArt kind="creatine"/><span>خصم 15%</span></div><div className="offer-mini"><ProductArt kind="mass"/><span>خصم 18%</span></div><div className="offer-mini"><ProductArt kind="vitamins"/><span>خصم 20%</span></div></section>
      <section className="why"><h2>لماذا كاربون جروب؟</h2><div><article><b>✓</b><strong>منتجات أصلية</strong><span>جودة موثوقة 100%</span></article><article><b>↗</b><strong>توصيل سريع</strong><span>إلى جميع المحافظات</span></article><article><b>✦</b><strong>دعم متخصص</strong><span>نساعدك في اختيارك</span></article><article><b>★</b><strong>أفضل العلامات</strong><span>عالمية ومحلية</span></article></div></section>
    </main>
    <footer><Logo/><span>CARBON GROUP NUTRITION — مكملاتك، قوتك، إنجازك.</span><button className="admin-link" onClick={()=>setView('admin')}>لوحة الإدارة</button></footer>
    <button className="chat-fab" onClick={()=>setChat(!chat)}><img src={`${import.meta.env.BASE_URL}assets/carbon-robot.webp`} alt="Carbon AI"/><span>مساعد كاربون الذكي</span></button>
    {chat&&<div className="chat-window"><div className="chat-head"><img src={`${import.meta.env.BASE_URL}assets/carbon-robot.webp`}/><div><b>مساعد كاربون الذكي</b><span>متصل الآن</span></div><button onClick={()=>setChat(false)}>×</button></div><div className="chat-body"><p className="bot">أهلاً بك! كيف أساعدك في اختيار مكملك اليوم؟</p><div className="quick"><button>أريد بروتين</button><button>قارن لي كرياتين</button><button>عروض اليوم</button></div></div><div className="chat-input">إكتب رسالتك... <span>➤</span></div></div>}
    <nav className="bottom-nav"><button className="active"><Icon name="grid"/><span>الرئيسية</span></button><button><Icon name="grid"/><span>الأقسام</span></button><button onClick={()=>setToast(`${compare.length} منتجات في المقارنة`)}><Icon name="compare"/><span>المقارنة</span>{compare.length>0&&<b>{compare.length}</b>}</button><button onClick={()=>setToast(`${cart.length} منتجات في السلة`)}><Icon name="cart"/><span>السلة</span>{cart.length>0&&<b>{cart.length}</b>}</button><button><Icon name="user"/><span>حسابي</span></button></nav>
    {toast&&<div className="toast">✓ {toast}</div>}
  </div>
}

function Admin({onBack}){ return <div className="admin-shell"><aside><Logo/><button className="back" onClick={onBack}>← العودة للمتجر</button>{['لوحة التحكم','الطلبات','المنتجات','الأقسام','العلامات التجارية','المخزون','العروض والكوبونات','المساعد الذكي','الإعلانات','التقييمات','التوصيل والدفع','الإعدادات','التقارير والنسخ الاحتياطي'].map((x,i)=><button className={i===0?'selected':''} key={x}><span>{['⌂','▣','▤','▦','◇','◉','%','◌','▥','★','⌁','⚙','▥'][i]}</span>{x}</button>)}</aside><section className="admin-main"><div className="admin-top"><div><small>الأربعاء، 30 سبتمبر 2026</small><h1>مرحباً بك في لوحة التحكم</h1></div><button className="admin-user"><Icon name="user"/> المدير العام</button></div><div className="kpis">{[['طلبات اليوم','24','+18%'],['إيرادات اليوم','1,240,000','+12%'],['بانتظار المعالجة','08','-4%'],['منتجات منخفضة','12','تنبيه']].map(([a,b,c])=><div className="kpi" key={a}><span>{a}</span><strong>{b}</strong><em>{c}</em></div>)}</div><div className="admin-grid"><div className="admin-card sales"><div className="card-head"><h2>نظرة عامة على المبيعات</h2><button>آخر 7 أيام⌄</button></div><div className="chart"><i style={{height:'38%'}}/><i style={{height:'55%'}}/><i style={{height:'45%'}}/><i style={{height:'68%'}}/><i style={{height:'52%'}}/><i style={{height:'83%'}}/><i style={{height:'72%'}}/></div></div><div className="admin-card"><div className="card-head"><h2>أحدث الطلبات</h2><button>عرض الكل</button></div>{['CG-2026-000123','CG-2026-000122','CG-2026-000121'].map((x,i)=><div className="order" key={x}><span>{x}</span><small>{['قيد التجهيز','تم التوصيل','جديد'][i]}</small><b>{['125,000','78,000','55,000'][i]} د.ع</b></div>)}</div></div><div className="admin-card table-card"><div className="card-head"><h2>إدارة المنتجات</h2><button className="primary">+ إضافة منتج</button></div><table><thead><tr><th>المنتج</th><th>الفئة</th><th>السعر</th><th>المخزون</th><th>الحالة</th></tr></thead><tbody>{products.slice(0,4).map(p=><tr key={p.id}><td><ProductArt kind={p.image}/><span>{p.ar}</span></td><td>{p.category}</td><td>{p.price.toLocaleString('en-US')} د.ع</td><td>{p.id*7+4}</td><td><em className="status">متوفر</em></td></tr>)}</tbody></table></div></section></div> }

createRoot(document.getElementById('root')).render(<App/>);
